<script lang="ts" setup>
import type { FeatureCard, JourneyStep, StatItem } from "../../types";
import { htmlForLocale } from "~/utils/htmlForLocale";

const { t, locale } = useI18n();

const destinationAddress = "Avenue des Arbanais 313, 83400 Hyeres, France";
const destinationQuery = "Lotissement Beausoleil, Avenue des Arbanais 313, Hyeres";
const mapEmbedUrl = `https://www.google.com/maps?q=${encodeURIComponent(destinationQuery)}&output=embed`;
const mapDirectionsUrl = `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(destinationQuery)}`;

const defaultLage = computed(() => htmlForLocale(locale.value, { de: `<p>Unsere Ferienhäuser liegen idyllisch auf der Halbinsel von Giens an der Avenue des Arbanais 313, nur etwa 15 Gehminuten vom Strand und vom Dorfzentrum entfernt.</p><p>Die Halbinsel von Giens befindet sich bei etwa 43°2′ nördlicher Breite an der Côte d'Azur im Département Var und gehört zu den südlichen Regionen des französischen Festlands.</p><p>Ein großer Teil der Halbinsel ist als Naturschutzgebiet ausgewiesen und steht unter besonderem Schutz. Besonders die Salinen und Feuchtgebiete zwischen den beiden Sanddämmen (Tombolos) bilden ein wichtiges Rückzugsgebiet für Zug- und Brutvögel.</p>`, fr: `<p>Nos maisons de vacances sont idylliquement situées sur la presqu'île de Giens, Avenue des Arbanais 313, à seulement environ 15 minutes à pied de la plage et du centre du village.</p><p>La presqu'île de Giens se trouve à environ 43°2′ de latitude nord sur la Côte d'Azur, dans le département du Var, et fait partie des régions les plus méridionales de la France métropolitaine.</p><p>Une grande partie de la presqu'île est classée en réserve naturelle et bénéficie d'une protection particulière. Les salines et les zones humides entre les deux cordons littoraux (tombolos) constituent un refuge important pour les oiseaux migrateurs et nicheurs.</p>` }));

const defaultAuto = computed(() => htmlForLocale(locale.value, { de: `<p>Die Anreise mit dem Auto ab Bern ist für viele Bewohner des Lotissement Beausoleil eine bevorzugte Option. Die Strecke führt hauptsächlich über Autobahnen und beträgt etwa 700 km. Die Fahrtzeit beträgt je nach Verkehr und Pausen etwa 7 bis 8 Stunden.</p>`, fr: `<p>Le trajet en voiture depuis Berne est, pour de nombreux habitants du Lotissement Beausoleil, l'option privilégiée. L'itinéraire emprunte principalement des autoroutes et compte environ 700 km. Selon le trafic et les pauses, le trajet dure environ 7 à 8 heures.</p>` }));

const defaultZug = computed(() => htmlForLocale(locale.value, { de: `<p>Die Anreise mit dem Zug ist eine bequeme Alternative. SNCF bietet hervorragende Verbindungen mit dem TGV an, oft mit nur zwei Umstiegen ab der Schweiz.</p>`, fr: `<p>Le voyage en train est une alternative confortable. La SNCF propose d'excellentes liaisons TGV, souvent avec seulement deux correspondances depuis la Suisse.</p>` }));

const defaultFlugzeug = computed(() => htmlForLocale(locale.value, { de: `<p>Der Flughafen <strong>Toulon-Hyères (TLN)</strong> liegt nur 15 Minuten von Giens entfernt und ist ideal für Kurztrips.</p><p>Alternativ bietet sich der Flughafen <strong>Marseille (MRS)</strong> an, der von Zürich oder Genf oft mehrmals täglich direkt angeflogen wird. Die Weiterreise nach Giens dauert von dort etwa 1h 15min mit dem Auto.</p>`, fr: `<p>L'aéroport <strong>Toulon-Hyères (TLN)</strong> se trouve à seulement 15 minutes de Giens et convient parfaitement aux courts séjours.</p><p>En alternative, l'aéroport <strong>Marseille (MRS)</strong> est souvent desservi plusieurs fois par jour depuis Zurich ou Genève. Le trajet jusqu'à Giens dure ensuite environ 1 h 15 en voiture.</p>` }));
