import { db } from "../../useFirebaseAdmin";

interface ContentResponse {
	id: string;
	content: string;
	translated?: { fr?: string };
	updatedAt: string;
	updatedBy: string;
}

export default defineEventHandler(async (event) => {
	try {
		const contentId = event.context.params?.id;
		const query = getQuery(event);
		const locale = (query.locale as string) || "de";

		if (!contentId) {
			throw createError({ statusCode: 400, message: "Content ID is required" });
		}

		const doc = await db.collection("content").doc(contentId).get();

		if (!doc.exists) {
			return {
				id: contentId,
				content: "",
				translated: { fr: "" },
				updatedAt: "",
				updatedBy: "",
			} as ContentResponse;
		}

		const data = doc.data() as any;

		// Handle legacy content format { de: "...", fr: "..." }
		if (typeof data.content === "object" && data.content?.de !== undefined) {
			return {
				id: doc.id,
				content: locale === "fr" ? (data.content.fr || data.content.de) : data.content.de,
				translated: { fr: data.content.fr || "" },
				updatedAt: data.updatedAt || "",
				updatedBy: data.updatedBy || "",
			} as ContentResponse;
		}

		// New format: content (German) + translated.fr (French, auto-generated by Firebase Extension)
		const germanContent = data.content || "";
		const frenchContent = data.translated?.fr || "";

		return {
			id: doc.id,
			content: locale === "fr" ? (frenchContent || germanContent) : germanContent,
			translated: { fr: frenchContent },
			updatedAt: data.updatedAt || "",
			updatedBy: data.updatedBy || "",
		} as ContentResponse;
	} catch (e: unknown) {
		throw createError({
			statusCode: (e as any).statusCode || 500,
			message: (e as any).message || "Internal Server Error",
		});
	}
});
